.PHONY: clean All

All:
	@echo "----------Building project:[ JAtextedit - Release ]----------"
	@cd "C:\Users\alberto\Documents\Alberto-C\JAtextedit" && "$(MAKE)" -f  "JAtextedit.mk"
clean:
	@echo "----------Cleaning project:[ JAtextedit - Release ]----------"
	@cd "C:\Users\alberto\Documents\Alberto-C\JAtextedit" && "$(MAKE)" -f  "JAtextedit.mk" clean
