.PHONY: clean All

All:
	@echo "----------Building project:[ JAtext - Release ]----------"
	@cd "JAtext" && "$(MAKE)" -f  "JAtext.mk"
clean:
	@echo "----------Cleaning project:[ JAtext - Release ]----------"
	@cd "JAtext" && "$(MAKE)" -f  "JAtext.mk" clean
